### ISSUE TITLE
failed to visit port 80 via ipv6

### ISSUE THREAD

**Issue by cyclinder** [DaoCloud/dao-2048#63]
```
bash-5.1# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether d6:f0:8a:58:cd:34 brd ff:ff:ff:ff:ff:ff
    inet 172.17.8.190/21 brd 172.17.15.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd00:1033::172:17:8:158/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::d4f0:8aff:fe58:cd34/64 scope link
       valid_lft forever preferred_lft forever
4: veth0@if185050: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 66:30:c3:c5:55:7d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::6430:c3ff:fec5:557d/64 scope link
       valid_lft forever preferred_lft forever
5: net1@if6: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether e6:db:9a:c2:34:66 brd ff:ff:ff:ff:ff:ff
    inet 172.81.0.195/16 brd 172.81.255.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fd00:81::172:81:0:144/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::e4db:9aff:fec2:3466/64 scope link
       valid_lft forever preferred_lft forever
bash-5.1# curl [fd00:81::172:81:0:144]
curl: (7) Failed to connect to fd00:81::172:81:0:144 port 80 after 0 ms: Connection refused
```

ipv4 works.

yaml:
```
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: dao2048-macvlan-overlay
      app.kubernetes.io/name: dao2048-macvlan-overlay
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        ipam.spidernet.io/ippool: |-
          {
              "interface": "net1",
              "ipv4pools": [
                "172-81-0-1"
              ],
              "ipv6pools": [
                "172-81-0-1-v6"
              ]
          }
        k8s.v1.cni.cncf.io/networks: kube-system/macvlan-vlan0
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dao2048-macvlan-overlay
        app.kubernetes.io/name: dao2048-macvlan-overlay
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: ghcr.io/daocloud/dao-2048:v1.1.0-beta.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: dao-macvlan-overlay
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_TIME
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
